spring:
  application:
    name: api_startkit

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

  devtools:
    restart:
      enabled: true

  messages:
    basename: messages/messages
    encoding: UTF-8

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG